# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b34d10753ab61146dfe9838df2dda25e242277f49761ad7a0281143873522dba33fe0596df805a5daf6bd26696edb87421eae5a4d80dcf630966dc7666a171db

test:
  secret_key_base: 990d97d55938eb7093ac046bf596424bbc6017a478993a10bb127dcab089f1803a7dd05a75f9fd4137c4906c88f537ae3406852f37b06ae733821376a266944c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
